---- [0] Tables ----
SELECT
	TABLE_SCHEMA,
	TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME <> 'sysdiagrams'
ORDER BY TABLE_SCHEMA, TABLE_NAME;
---- [1] Table Columns ----
SELECT
	C.TABLE_SCHEMA,
	C.TABLE_NAME,
	C.COLUMN_NAME,
	C.DATA_TYPE,
	ISNULL(C.CHARACTER_MAXIMUM_LENGTH, 0) AS CHARACTER_MAXIMUM_LENGTH,
	C.COLUMN_DEFAULT,
	C.IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS C
	INNER JOIN INFORMATION_SCHEMA.TABLES T ON T.TABLE_SCHEMA = C.TABLE_SCHEMA AND T.TABLE_NAME = C.TABLE_NAME
WHERE T.TABLE_TYPE = 'BASE TABLE' AND T.TABLE_NAME <> 'sysdiagrams'
ORDER BY C.TABLE_SCHEMA, C.TABLE_NAME, C.ORDINAL_POSITION;
---- [2] Constraints ----
SELECT
	C.TABLE_SCHEMA,
	C.TABLE_NAME,
	C.CONSTRAINT_TYPE,
	C.CONSTRAINT_NAME,
	U.COLUMN_NAME,
	R.TABLE_NAME AS REFERENTIAL_TABLE_NAME,
	R.TABLE_SCHEMA AS REFERENTIAL_TABLE_SCHEMA
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS C
	LEFT OUTER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE U ON C.TABLE_SCHEMA = U.TABLE_SCHEMA AND C.TABLE_NAME = U.TABLE_NAME AND C.CONSTRAINT_NAME = U.CONSTRAINT_NAME
	LEFT OUTER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS F ON C.CONSTRAINT_NAME = F.CONSTRAINT_NAME
	LEFT OUTER JOIN INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE R ON F.UNIQUE_CONSTRAINT_NAME = R.CONSTRAINT_NAME
WHERE
	CONSTRAINT_TYPE <> 'CHECK' AND
	C.TABLE_NAME <> 'sysdiagrams'
ORDER BY C.TABLE_SCHEMA, C.TABLE_NAME, C.CONSTRAINT_NAME, U.ORDINAL_POSITION;
---- [3] Table Indexes ----
SELECT
	OBJECT_SCHEMA_NAME(C.[object_id]) AS TABLE_SCHEMA,
	OBJECT_NAME(C.[object_id]) AS TABLE_NAME,
	I.name AS INDEX_NAME,
	S.name AS COLUMN_NAME
FROM sys.index_columns C
	LEFT OUTER JOIN sys.indexes I ON C.[object_id] = I.[object_id] AND C.index_id = I.index_id
	LEFT OUTER JOIN sys.columns S ON C.[object_id] = S.[object_id] AND C.column_id = S.column_id
WHERE
	OBJECTPROPERTY(C.[object_id], 'IsUserTable') = 1 AND
	OBJECT_NAME(C.[object_id]) <> 'sysdiagrams' AND
	I.[type] in (1, 2) AND
	I.is_primary_key = 0
ORDER BY
	OBJECT_SCHEMA_NAME(C.[object_id]),
	OBJECT_NAME(C.[object_id]),
	C.index_id;
---- [4] Views ----
SELECT
	TABLE_SCHEMA,
	TABLE_NAME
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_TYPE = 'VIEW'
	ORDER BY TABLE_SCHEMA, TABLE_NAME;
---- [5] View Columns ----
SELECT
	C.TABLE_SCHEMA,
	C.TABLE_NAME,
	C.COLUMN_NAME,
	C.DATA_TYPE,
	ISNULL(C.CHARACTER_MAXIMUM_LENGTH, 0) AS CHARACTER_MAXIMUM_LENGTH,
	C.IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS C
	INNER JOIN INFORMATION_SCHEMA.TABLES T ON T.TABLE_SCHEMA = C.TABLE_SCHEMA AND T.TABLE_NAME = C.TABLE_NAME
WHERE T.TABLE_TYPE = 'VIEW'
ORDER BY C.TABLE_SCHEMA, C.TABLE_NAME, C.ORDINAL_POSITION;
---- [6] View Indexes ----
SELECT
	OBJECT_SCHEMA_NAME(C.[object_id]) AS TABLE_SCHEMA,
	OBJECT_NAME(C.[object_id]) AS TABLE_NAME,
	I.name AS INDEX_NAME,
	S.name AS COLUMN_NAME
FROM sys.index_columns C
LEFT OUTER JOIN sys.indexes I ON C.[object_id] = I.[object_id] AND C.index_id = I.index_id
LEFT OUTER JOIN sys.columns S ON C.[object_id] = S.[object_id] AND C.column_id = S.column_id
WHERE
	OBJECTPROPERTY(C.[object_id], 'IsView') = 1 AND
	OBJECT_NAME(C.[object_id]) <> 'sysdiagrams' AND
	I.[type] in (1, 2) AND
	I.is_primary_key = 0
ORDER BY
	OBJECT_SCHEMA_NAME(C.[object_id]),
	OBJECT_NAME(C.[object_id]),
	C.index_id;
---- [7] Procedures ----
SELECT
	SPECIFIC_SCHEMA,
	SPECIFIC_NAME,
	ROUTINE_DEFINITION
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_NAME NOT IN ('sp_upgraddiagrams', 'sp_helpdiagrams', 'sp_helpdiagramdefinition', 'sp_alterdiagram', 'sp_creatediagram', 'sp_dropdiagram', 'sp_renamediagram')
ORDER BY SPECIFIC_SCHEMA, SPECIFIC_NAME;
---- [8] Procedure Parameters ----
SELECT
	SPECIFIC_SCHEMA,
	SPECIFIC_NAME,
	PARAMETER_NAME,
	DATA_TYPE,
	ISNULL(CHARACTER_MAXIMUM_LENGTH, 0) AS CHARACTER_MAXIMUM_LENGTH,
	PARAMETER_MODE
FROM INFORMATION_SCHEMA.PARAMETERS
ORDER BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ORDINAL_POSITION;
---- [9] Descriptions ----
SELECT
	OBJECTPROPERTYEX(major_id, 'BaseType') AS BaseType,
	OBJECT_SCHEMA_NAME(major_id) AS [Schema],
	OBJECT_NAME(major_id) AS MajorName,
	COL_NAME(major_id, minor_id) AS MinorName,
	[value] AS [Value]
FROM sys.extended_properties
WHERE [name] = 'MS_Description';
---- [10] Enumeratioins [11] EnumeratioinMembers ----
IF
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Ref_Enumeration') AND
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Ref_EnumerationMember')
BEGIN
	SELECT
		[Name],
		BaseType,
		HasFlagsAttribute,
		[Description]
	FROM Ref_Enumeration;
	SELECT
		EnumerationName,
		[Name],
		[Value],
		[Description]
	FROM Ref_EnumerationMember
	ORDER BY EnumerationName, [Value];
END
ELSE
BEGIN
	SELECT -1;
END